# Run a couple of linters on code in repo
# * shellcheck and shfmt for shell scripts
# * YAPF for Python scripts
name: Lint checks
on: [push, pull_request]
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: shellcheck
      uses: bewuethr/shellcheck-action@v1
  yapf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: yapf
      uses: AlexanderMelde/yapf-action@master
  shfmt-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.14.2'
    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Run shfmt
      run: |
        GO111MODULE=on go get mvdan.cc/sh/v3/cmd/shfmt
        while read -r f; do
          PATH=$HOME/go/bin:$PATH shfmt -ci -d -i 4 $f
        done < <(find . -type f -name "*.sh")
